### ISSUE TITLE
Unable to pickle AMFClassifier. 

### ISSUE THREAD

**Issue by w-feijen** [onelearn/onelearn#61]
I would like to save the AMFClassifier, but am unable to pickle it. I have also tried to use dill or joblib, but they also don't seem to work. 

Is there maybe another way to somehow export the AMFClassifier in any way, such that I can save it and load it in another kernel?

Below I added a snippet of code which reproduces the error. Note that only _after_ the partial_fit method an error occurs when pickling. When the AMFClassifier has not been fit yet, pickling happens without problems, however, exporting an empty model is pretty useless.

Any help or tips is much appreciated.
```
from onelearn import AMFClassifier
import dill as pickle
from sklearn import datasets


iris = datasets.load_iris()
X = iris.data
y = iris.target

amf = AMFClassifier(n_classes=3)

dump = pickle.dumps(amf)
amf = pickle.loads(dump)

amf.partial_fit(X,y)

dump = pickle.dumps(amf)
amf = pickle.loads(dump)
```

**Comment by stephanegaiffas** [comment]
Hi, I managed to do it, if you update onelearn's version to 0.3 you will have save and load methods to save and load using pickle AMFClassifier and AMFRegressor.
